#!/bin/bash

# Choose between

#./mill --no-server runMainLocal com.mchange.feedletter.Main "$@"
#./mill --no-server runMainBackground com.mchange.feedletter.Main "$@"
#./mill --no-server runMain com.mchange.feedletter.Main "$@"

# Style commands need to be run with the -w flag, but are managed
# by the separate script feedletter-style

# A bit (well, very) fragile...

MAINCMD="$0"
FEEDLETTER_DIR="$(dirname $MAINCMD)"
EXECNAME="$(basename $MAINCMD)"

cd "$FEEDLETTER_DIR"

case $1 in
    --secrets)
        SUBCMD="$3"
        FIRSTARG="$4"
        ;;
    --secrets*)
        SUBCMD="$2"
        FIRSTARG="$3"
        ;;
    *)
        SUBCMD="$1"
        FIRSTARG="$2"
        ;;
esac

if [[ "$EXECNAME" == "feedletter" ]]; then
    if [[ "$SUBCMD" == "edit-subscribable" ]]; then  # we need native streams...
        ./mill --no-daemon --ticker=false runMainLocal com.mchange.feedletter.Main "$@"
    elif [[  "$SUBCMD" == "daemon" && "$FIRSTARG" == "--fork" ]]; then
        ./mill --no-daemon --ticker=false runMainDaemon com.mchange.feedletter.Main "$@"
    else
        ./mill --no-daemon --ticker=false runMain com.mchange.feedletter.Main "$@"
    fi
else
    echo "Expected this command to be 'feedletter'."
fi


