#!/bin/bash

# Choose between

#./millw --no-server runMainLocal com.mchange.feedletter.Main "$@"
#./millw --no-server runMainBackground com.mchange.feedletter.Main "$@"
#./millw --no-server runMain com.mchange.feedletter.Main "$@"

# Style commands need to be run with the -w flag, but are managed
# by the separate script feedletter-style

# A bit (well, very) fragile...

MAINCMD=$0

if [[ "$1" == "--secrets" ]]; then
    SUBCMD="$3"
    FIRSTARG="$4"
else
    SUBCMD="$1"
    FIRSTARG="$2"
fi

if [[ "$MAINCMD" == "./feedletter" || "$MAINCMD" == "feedletter" ]]; then
    if [[ "$SUBCMD" == "edit-subscribable" ]]; then  # we need native streams...
        ./millw --no-server runMainLocal com.mchange.feedletter.Main "$@"
    elif [[  "$SUBCMD" == "daemon" && "$FIRSTARG" == "--fork" ]]; then
        ./millw --no-server runMainBackground com.mchange.feedletter.Main "$@"
    else
        ./millw --no-server runMain com.mchange.feedletter.Main "$@"
    fi
else
    echo "Expected this command to be 'feedletter' or './feedletter'"
fi


